import type { TacticAxis } from "./axes";

/*
 * Trilingual (en/gu/hi) lexicons, one per tactic axis. Same regex idiom as the
 * rule groups (rules/*.ts): module-level `readonly RegExp[]`, gu/hi/en variants
 * interleaved, flagged giu/gu. Reminder from rules/credential.ts: \b is
 * ASCII-only in JS, so standalone Devanagari/Gujarati tokens use explicit
 * whitespace/danda boundaries, never \b.
 *
 * Overlap across axes is intentional — a real scam lights up several at once.
 */

const urgency: readonly RegExp[] = [
  /within\s?\d+\s?(?:hours?|hrs?|minutes?|mins?)/giu,
  /in\s?the\s?next\s?\d+\s?(?:hours?|minutes?)/giu,
  /\d+\s?(?:hours?|hrs?)\s?(?:left|remaining)/giu,
  /immediately/giu,
  /\b(?:right\s?)?now\b/giu,
  /\btoday\b/giu,
  /\btonight\b/giu,
  /urgent(?:ly)?/giu,
  /last\s?chance/giu,
  /act\s?(?:now|immediately|fast)/giu,
  /hurry/giu,
  /expire[sd]?\s?(?:today|soon|now|tomorrow)/giu,
  /before\s?(?:midnight|it'?s?\s?too\s?late)/giu,
  /તાત્કાલિક/gu,
  /તાકીદ/gu,
  /આજે\s?જ/gu,
  /તરત\s?જ/gu,
  /છેલ્લી\s?તક/gu,
  /\d+\s?કલાકમાં/gu,
  /तुरंत/gu,
  /तत्काल/gu,
  /आज\s?ही/gu,
  /अभी\s?ही/gu,
  /आखिरी\s?मौका/gu,
  /\d+\s?घंटे\s?में/gu,
  /जल्दी/gu,
];

const authority: readonly RegExp[] = [
  /\brbi\b/giu,
  /reserve\s?bank/giu,
  /\btrai\b/giu,
  /\bcbi\b/giu,
  /\bed\b\s?(?:department|office)/giu,
  /\bpolice\b/giu,
  /cyber\s?(?:cell|crime|police|branch)/giu,
  /income\s?tax/giu,
  /\bepfo?\b/giu,
  /\bgst\b/giu,
  /\bkyc\s?(?:department|dept|team)/giu,
  /electricity\s?(?:board|department)/giu,
  /(?:fedex|dhl|blue\s?dart|courier|customs?)\b/giu,
  /\bofficer\b/giu,
  /\binspector\b/giu,
  /\b(?:sbi|icici|hdfc|axis|pnb|kotak|bank)\b/giu,
  /government|govt\.?/giu,
  /(?:this\s?is|calling\s?from|on\s?behalf\s?of)\b/giu,
  /અધિકારી/gu,
  /પોલીસ/gu,
  /આવકવેરા/gu,
  /વિભાગમાંથી/gu,
  /બેંક/gu,
  /अधिकारी/gu,
  /पुलिस/gu,
  /आयकर/gu,
  /विभाग\s?से/gu,
  /बैंक/gu,
];

const fear: readonly RegExp[] = [
  /\bblock(?:ed|ing)?\b/giu,
  /\bsuspend(?:ed)?\b/giu,
  /\bfreeze|frozen\b/giu,
  /\bde-?activat(?:e|ed|ion)\b/giu,
  /disconnect(?:ed|ion)?/giu,
  /\barrest(?:ed)?\b/giu,
  /(?:arrest|non[\s-]?bailable)\s?warrant/giu,
  /warrant/giu,
  /legal\s?action/giu,
  /\bfir\b/giu,
  /penalty|fine\b/giu,
  /seized|seizure|held\s?(?:at|by)/giu,
  /illegal|prohibited|narcotics?|drugs?/giu,
  /money\s?laundering/giu,
  /will\s?be\s?(?:blocked|closed|deactivated|suspended)/giu,
  /બંધ\s?થઈ/gu,
  /ધરપકડ/gu,
  /વોરંટ/gu,
  /કાનૂની/gu,
  /बंद\s?हो/gu,
  /गिरफ्तार/gu,
  /गिरफ़्तारी/gu,
  /वारंट/gu,
  /कानूनी/gu,
  /कार्रवाई/gu,
];

const reward: readonly RegExp[] = [
  /lotter/giu,
  /\bkbc\b/giu,
  /lucky\s?draw/giu,
  /\bprize\b/giu,
  /you\s?(?:have\s?)?won/giu,
  /\bjackpot\b/giu,
  /congratulations?/giu,
  /cashback/giu,
  /\brefund\b/giu,
  /free\s?(?:gift|gas\s?cylinder|recharge)/giu,
  /reward\s?points?/giu,
  /\bbonus\b/giu,
  /\bsubsidy\b/giu,
  /loan\s?(?:approved|of\s?rs)/giu,
  /pre[\s-]?approved/giu,
  /guaranteed\s?(?:profit|return)/giu,
  /double\s?your\s?money/giu,
  /earn\s?(?:₹|rs\.?|rupees)?\s?[\d,]+\s?(?:daily|per\s?day|a\s?day)/giu,
  /લોટરી/gu,
  /ઇનામ/gu,
  /જીત્યા/gu,
  /અભિનંદન/gu,
  /રિફંડ/gu,
  /लॉटरी/gu,
  /इनाम/gu,
  /जीत\w*/gu,
  /बधाई/gu,
  /रिफंड/gu,
  /मुफ़्त|मुफ्त/gu,
];

const secrecy: readonly RegExp[] = [
  /do\s?not\s?tell\s?(?:anyone|any\s?one|anybody|family)/giu,
  /don'?t\s?tell\s?(?:anyone|anybody|family)/giu,
  /do\s?not\s?(?:inform|disclose)/giu,
  /keep\s?(?:this|it)\s?(?:a\s?)?secret/giu,
  /not\s?even\s?(?:your\s?)?(?:family|bank)/giu,
  /between\s?(?:us|you\s?and\s?me)/giu,
  /without\s?(?:informing|telling)/giu,
  /confidential/giu,
  /કોઈને\s?(?:કહેશો|જણાવશો)\s?નહીં/gu,
  /કોઈને\s?ન\s?કહો/gu,
  /ગુપ્ત\s?રાખ/gu,
  /किसी\s?को\s?(?:मत|न|नहीं)\s?बता/gu,
  /किसी\s?को\s?मत\s?बताना/gu,
  /गुप्त\s?रख/gu,
  /राज़\s?रख/gu,
];

const credential: readonly RegExp[] = [
  /\botp\b/giu,
  /one[\s-]?time\s?password/giu,
  /\bcvv\b/giu,
  /\bm-?pin\b/giu,
  /\b(?:upi|atm)[\s-]?pin\b/giu,
  /\bpin\b/giu,
  /password/giu,
  /verification\s?code/giu,
  /\d{2,}[\s-]?digit\s?(?:card|code)/giu,
  /card\s?(?:number|details)/giu,
  /\bany\s?desk\b/giu,
  /\bteam\s?viewer\b/giu,
  /\bquick\s?support\b/giu,
  /screen\s?shar(?:e|ing)/giu,
  /ઓ\.?ટી\.?પી\.?/gu,
  /પિન/gu,
  /પાસવર્ડ/gu,
  /ओ\.?टी\.?पी\.?/gu,
  /पिन/gu,
  /पासवर्ड/gu,
];

const trust: readonly RegExp[] = [
  /i\s?am\s?(?:a\s?)?(?:poor|garib)/giu,
  /please\s?help/giu,
  /\bbrother\b|\bbhai\b/giu,
  /\bsister\b/giu,
  /\buncle\b|\baunty\b/giu,
  /\bbeta\b/giu,
  /this\s?is\s?your\s?(?:uncle|relative|friend)/giu,
  /i\s?(?:lost|changed)\s?my\s?(?:phone|number)/giu,
  /my\s?new\s?number/giu,
  /(?:indian\s?)?army|navy|crpf|subedar|major|captain/giu,
  /trust\s?me/giu,
  /i\s?will\s?return\s?(?:it|tomorrow)/giu,
  /ગરીબ/gu,
  /મદદ\s?કરો/gu,
  /ભાઈ/gu,
  /गरीब/gu,
  /मदद\s?कर/gu,
  /भाई/gu,
  /भरोसा/gu,
];

const irreversibility: readonly RegExp[] = [
  /\b(?:upi|atm)[\s-]?pin\b/giu,
  /enter\s?(?:your\s?)?pin\b(?!\s?code)/giu,
  /\bapprove\b|\baccept\b/giu,
  /collect\s?request|payment\s?request/giu,
  /scan\s?(?:this|the)?\s?qr/giu,
  /\bqr\s?code\b/giu,
  /\bbitcoin\b|\bbtc\b|crypto/giu,
  /gift\s?card/giu,
  /(?:google\s?pay|phonepe|paytm|gpay)/giu,
  /transfer\s?(?:the\s?)?(?:money|amount|funds)/giu,
  /send\s?(?:it\s?)?back|return\s?the\s?money/giu,
  /pay\s?(?:now|₹|rs\.?)/giu,
  /સ્વીકાર/gu,
  /મંજૂર/gu,
  /પિન\s?નાખ/gu,
  /स्वीकार/gu,
  /मंजूर/gu,
  /पिन\s?डाल/gu,
];

export const AXIS_LEXICONS: Record<TacticAxis, readonly RegExp[]> = {
  urgency,
  authority,
  fear,
  reward,
  secrecy,
  credential,
  trust,
  irreversibility,
};
